### ISSUE TITLE
Create summary data

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/CDC500#6]
Create summary files from the CDC500 tract-level file.

**Comment by rpitingolo** [comment]
@ptatian Accidentally posted this on the wrong issue, so I deleted and re-posted here. We've read in the data and saved the base file here: L:\Libraries\CDC500\Data

I'm stuck on how to create the summary files from this. Is %Create_all_summary_from_tracts the correct macro to use? And relatedly is there instructions anywhere on how to define the parameters? cc: @maggiesu0725

**Comment by ptatian** [comment]
@rpitingolo Yes, it's a tract-level data set so you should be able to use %Create_all_summary_from_tracts(). I'm afraid it's not a well-documented macro. Here's some tips for using it. 

Most of the parameters are the same as %Transform_geo_data()

```
  lib=,  /** Library for input and output data sets **/
  data_pre=,  /** Prefix for data set names **/
  data_label=,  /** Data set label prefix **/
  count_vars=, /** Variables that provide counts of persons, HHs, etc. **/
  prop_vars=,  /** Variables that are proportions or percentages **/
  calc_vars=,  /** Statements for creating calculated vars (optional) **/
  calc_vars_labels=,  /** Variable labels for calculated vars (optional) **/
  tract_yr=,  /** Year of source data census tracts: 2000 or 2010 **/
  revisions=,  /** Description of file revisions **/
```

Note that data_pre= needs to be the first part of the name of both the source (tract) and output data sets. So, the source data set needs to follow the **XXXX_sum_tr10** naming style, and the macro assumes **you've already created that file**. 

Also, I note that the **Cdc500.Cdc500_2017** data set does not have proper var labels. Those should be added. 

Look at **L:\Libraries\NCDB\Prog\Ncdb_sum_all.sas** as an example of how to use this macro. 

Let me know if you have other questions.

**Comment by rpitingolo** [comment]
@ptatian thanks, Peter! We'll add the var labels. Sorry we forgot about those. 

@maggiesu0725 do you feel comfortable enough with these tips to try to create t program to create the summary files? If not we can work on it together.

**Comment by ptatian** [comment]
Thanks, @rpitingolo and @maggiesu0725. FYI, additional info on the %Transform_geo_data() parameters (which, as I mentioned, are the same as many of those in the tract macro), can be found in **L:\Uiautos\Html\Transform_geo_data.htm**.

**Comment by rpitingolo** [comment]
@maggiesu0725 I think we are close on this. You can use the pct_vars macro to list out the variables you want in the summary file (all of them, probably). Also change the data_pre paramter to match the file you are creating under the other issue. After that tag me and I will look again. Thanks!
